name: Build and Push Target Image

permissions:
  id-token: write
  contents: read
on:
  # For automated/reusable workflow calls.
  workflow_call:
    inputs:
      image-name:
        description: The name of the image to build.
        required: true
        type: string
      build-args:
        description: Optional list of arguments to provide to the build.
        required: false
        type: string
      upstream-updated:
        description: If the given image's VERSION is a symlink, can be easier just to receive the info from the given job.
        required: false
        type: string
        default: 'false'
      image-flavor:
        description: Image flavor, as per `docker/metadata-action`'s `flavor` input.
        require: false
        type: string
    outputs:
      updated:
        description: If we detected an update.
        value: ${{ jobs.tags.outputs.updated }}
      tags:
        description: The "{image}:{tag}" image tags.
        value: ${{ jobs.tags.outputs.tags }}
      image-info:
        description: Info about the built image.
        value: ${{ jobs.build-push.image-info }}
      meta-json:
        description: Build tag/meta info, as per `docker/metadata-action`'s `json` output.
        value: ${{ jobs.tags.outputs.meta-json }}
  # For manual invocations.
  workflow_dispatch:
    inputs:
      image-name:
        description: The name of the image to build.
        required: true
        type: choice
        options:
          - activemq
          - alpaca
          - cantaloupe
          - crayfish
          - drupal-base
          - drupal-base-dev
          - solr
          - solr-ctda
      build-args:
        description: Optional list of arguments to provide to the build.
        required: false
        type: string
      upstream-updated:
        description: If the given image's VERSION is a symlink, can be easier just to receive the info from the given job.
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      updated: ${{ steps.check-tags.outputs.updated }}
      tags: ${{ steps.meta.outputs.tags }}
      meta-json: ${{ steps.meta.outputs.json }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check if image tags updated
        id: check-tags
        run: |
          files_changed=$(git diff-tree --no-commit-id --name-only --diff-filter=d -r ${{ github.event.before }} ${{ github.sha }})
          if grep "^images/$IMAGE_NAME/VERSION\$" <<< "$files_changed"; then
            echo "updated=true" >> "$GITHUB_OUTPUT"
          else
            echo "updated=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          IMAGE_NAME: ${{ inputs.image-name }}
      - name: Build tag structure
        id: tag-structure
        run: |
          head -n1 images/${{ inputs.image-name }}/VERSION | read TAG
          cat - <<EOF
          tags<<EOT
          type=semver,pattern={{version}},value=$TAG
          type=semver,pattern={{major}}.{{minor}},value=$TAG
          type=semver,pattern={{major}},value=$TAG
          EOT
          EOF >> "$GITHUB_OUTPUT"
      - name: Get tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DOCKER_REGISTRY_URL }}/${{ inputs.image-name }}
          tags: ${{ steps.tag-structure.outputs.tags }}
          flavor: ${{ inputs.image-flavor }}

  build-push:
    runs-on: ubuntu-latest
    needs: tags
    if: needs.tags.outputs.updated == 'true' || inputs.upstream-updated == 'true'
    outputs:
      image-info: ${{ toJson(steps.image-build.outputs) }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        uses: docker/build-push-action@v4
        id: image-build
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ needs.tags.outputs.tags }}
          context: "{{defaultContext}}:images/${{ inputs.image-name }}"
          build-args: ${{ inputs.build-args }}

      - name: Create summary
        run: |
          cat <<EOF >> $GITHUB_STEP_SUMMARY
          ## Images Pushed
          | Image  | Tags |
          | ------------- | ------------- |
          | $IMAGE_REPO | $(awk -F ":" '{print $NF}' <<< "$TAGS" | sed -z 's/\n/, /g;s/, *$/\n/' ) |
          EOF
        env:
          IMAGE_REPO: ${{ vars.DOCKER_REGISTRY_URL }}/${{ inputs.image-name }}
          TAGS: ${{ needs.tags.outputs.tags }}

