---
name: Dependabot Pull-Request Ticket
on: pull_request
permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Create Issue
        uses: discoverygarden/create-issue@v1
        with:
          project: IT
          summary: "[${{ github.repository }}] Dependabot update"
          description: |
            Dependabot generated a PR to update a dependency.
          transition: "Request QA Review"
          deployment-instructions: "N/A"
          jira-url: ${{ vars.JIRA_BASE_URL }}
          jira-user: ${{ vars.JIRA_USER_EMAIL }}
          jira-token: ${{ secrets.JIRA_API_TOKEN }}
          slack-webhook: ${{ secrets.FEED_WORKFLOW_WEBHOOK }}
          guthub-token: ${{ github.token }}
