name: Docker

permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - cdi9-22-cicd
    paths:
      - 'images/**/VERSION'
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the images
        run: |
          echo "##Images Pushed" >> $GITHUB_STEP_SUMMARY
          echo "| First Header  | Second Header |" >> $GITHUB_STEP_SUMMARY
          echo "| ------------- | ------------- |" >> $GITHUB_STEP_SUMMARY

          for versionFilePath in $(git diff-tree --no-commit-id --name-only --diff-filter=d -r ${{ github.event.before }} ${{ github.sha }} | grep 'VERSION' );
          do
            folder=${versionFilePath%"/VERSION"}
            IMAGE_NAME=${folder##*/}
            echo "::group::$IMAGE_NAME"

            tmpName="image-$RANDOM"
            docker buildx build $folder --file $folder/Dockerfile --tag $tmpName
            IMAGE_ID=${{ vars.DOCKER_REGISTRY_URL }}/$IMAGE_NAME
            VERSION=$(cat $versionFilePath)

            while IFS= read -r VERSION
            do
              echo IMAGE_ID=$IMAGE_ID
              echo VERSION=$VERSION

              docker tag $tmpName $IMAGE_ID:$VERSION
              docker push $IMAGE_ID:$VERSION
            done < "$versionFilePath"

            echo "| $IMAGE_ID | $(sed -z 's/\n/, /g;s/,$/\n/' $versionFilePath) |" >> $GITHUB_STEP_SUMMARY
            echo "::endgroup::"
          done;
