name: Occasionally rebuild images

permissions:
  id-token: write
  contents: read
on:
  schedule:
    - cron: '47 4 1 * *'

jobs:
  activemq:
    uses: ./.github/workflows/rebuild-image.yml
    with:
      image-name: activemq
  alpaca:
    uses: ./.github/workflows/rebuild-image.yml
    with:
      image-name: alpaca
  cantaloupe:
    uses: ./.github/workflows/rebuild-image.yml
    with:
      image-name: cantaloupe
  crayfish:
    uses: ./.github/workflows/rebuild-image.yml
    with:
      image-name: crayfish
  drupal-base:
    uses: ./.github/workflows/rebuild-image.yml
    with:
      image-name: drupal-base
  drupal-base-dev:
    uses: ./.github/workflows/rebuild-image.yml
    with:
      image-name: drupal-base
      build-args: |
        "BASE_IMAGE=${{ fromJSON(fromJSON(needs.drupal-base.outputs.image-names)['split'])[0] }}"
      image-flavor: |
        prefix=dev-,onlatest=true
    needs: drupal-base
